import { fetchNOMIS } from '@/lib/fetch-nomis';
import { fetchIMD } from '@/lib/fetch-imd';
import { fetchGVA } from '@/lib/fetch-gva';
import { fetchCrime } from '@/lib/fetch-crime';
import { fetchNEETCity, fetchYouthClaimants } from '@/lib/fetch-neet';
import { mergeData } from '@/lib/data';
import { EDUCATION_2021 } from '@/lib/education-data';
import type { DataSources, DataMeta, EduDataMeta, NeetCityData, CrimeWard } from '@/lib/types';
import Dashboard from '../components/Dashboard';
import crimeWardsData from '../../public/data/crime-wards.json';

export const revalidate = 3600;

export default async function DashboardPage() {
  const dsrc: DataSources = { nomis: 'cached', imd: 'cached', gva: 'cached', crime: 'cached', neet: 'cached' };
  const dsmeta: DataMeta = {
    nomis: { count: null, date: null, err: null },
    imd: { lsoas: null, wards: null, err: null },
    gva: { count: null, err: null },
    crime: { count: null, err: null },
    neet: { count: null, bham_neet_pct: null, bham_year: '—', err: null },
  };

  const [nomisResult, imdResult, gvaResult, crimeResult, youthResult, neetCityResult] = await Promise.allSettled([
    fetchNOMIS(),
    fetchIMD(),
    fetchGVA(),
    fetchCrime(),
    fetchYouthClaimants(),
    fetchNEETCity(),
  ]);

  let nMap = null, nDate = 'Jan 2026';
  if (nomisResult.status === 'fulfilled') {
    nMap = nomisResult.value.map;
    nDate = nomisResult.value.date;
    dsrc.nomis = 'live';
    dsmeta.nomis = { count: nomisResult.value.count, date: nDate, err: null };
  } else {
    dsmeta.nomis.err = String(nomisResult.reason);
  }

  let iMap = null;
  if (imdResult.status === 'fulfilled') {
    iMap = imdResult.value.map;
    dsrc.imd = 'live';
    dsmeta.imd = { lsoas: imdResult.value.lsoas, wards: imdResult.value.wards, err: null };
  } else {
    dsmeta.imd.err = String(imdResult.reason);
  }

  let gMap = null, popMap = null;
  if (gvaResult.status === 'fulfilled') {
    gMap = gvaResult.value.map;
    popMap = gvaResult.value.popMap;
    dsrc.gva = 'live';
    dsmeta.gva = { count: gvaResult.value.count, year: gvaResult.value.year, err: null };
  } else {
    dsmeta.gva.err = String(gvaResult.reason);
  }

  let crimeMap = null;
  if (crimeResult.status === 'fulfilled') {
    crimeMap = crimeResult.value.map;
    dsrc.crime = 'live';
    dsmeta.crime = { count: crimeResult.value.count, err: null };
  } else {
    dsmeta.crime.err = String(crimeResult.reason);
  }

  let youthMap = null;
  if (youthResult.status === 'fulfilled' && youthResult.value.count > 0) {
    youthMap = youthResult.value.map;
    dsrc.neet = 'live';
    dsmeta.neet = { count: youthResult.value.count, bham_neet_pct: null, bham_year: '—', err: null };
  } else if (youthResult.status === 'rejected') {
    dsmeta.neet.err = String(youthResult.reason);
  }

  let neetData: NeetCityData = { bham_neet_pct: 6.1, bham_year: '2022/23', wmca_neet_pct: 5.4, source: 'cached' };
  if (neetCityResult.status === 'fulfilled') {
    neetData = neetCityResult.value;
    if (neetData.bham_neet_pct != null) {
      dsmeta.neet = { ...dsmeta.neet, bham_neet_pct: neetData.bham_neet_pct, bham_year: neetData.bham_year };
    }
  }

  // Education: committed Census 2021 snapshot (lib/education-data.ts) — read directly,
  // no live fetch or fallback. Census is frozen until 2031.
  const eduWards = EDUCATION_2021;
  const eduMeta: EduDataMeta = { wards: EDUCATION_2021.length, vintage: 'Census 2021' };

  const wards = mergeData(nMap, iMap, gMap, popMap, crimeMap, youthMap);

  // Real ward-level crime — official 69 wards, data.police.uk (public/data/crime-wards.json,
  // generated by scripts/fetch-crime-wards.mjs). Used by the crime dashboard directly.
  const crimeWards: CrimeWard[] = (crimeWardsData.wards as Array<{
    ward_code: string; ward_name: string; population: number | null;
    rate_per_1000: number | null; rank?: number; categories?: Record<string, number>;
  }>)
    .filter(w => w.rate_per_1000 != null)
    .map(w => ({
      ward_code: w.ward_code,
      ward_name: w.ward_name,
      population: w.population ?? 0,
      crime_rate_per_1000: w.rate_per_1000 as number,
      crime_rank: w.rank ?? 0,
      crime_categories: w.categories ?? {},
    }));

  return <Dashboard wards={wards} dsrc={dsrc} dsmeta={dsmeta} nomisDate={nDate} eduWards={eduWards} eduMeta={eduMeta} neetData={neetData} crimeWards={crimeWards} crimeMonth={crimeWardsData.month} />;
}
